spring:
  boot:
    admin:
      ui:
        theme:
          color: "#451B66"
          background:
            start: "#CB6CD8"
            stop: "#451B66"
          palette:
            main-color-lighter: "#fdf2f8"
            main-color-light: "#f9a8d4"
            main-color: "#ec4899"
            main-color-dark: "#be185d"
            main-color-darker: "#9d174d"
